// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBralwIbvKgQnrgmdqdjUD7pn2psf2jSDA',
    appId: '1:466493882118:web:0186b3f08e1e1a23dd6887',
    messagingSenderId: '466493882118',
    projectId: 'messenger-bc263',
    authDomain: 'messenger-bc263.firebaseapp.com',
    storageBucket: 'messenger-bc263.appspot.com',
    measurementId: 'G-CZTW5JMGRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4X5t2nUxjEbbcwTN9JJ0e7qwGb-HzCI',
    appId: '1:466493882118:android:74ccb299ce93d55edd6887',
    messagingSenderId: '466493882118',
    projectId: 'messenger-bc263',
    storageBucket: 'messenger-bc263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PaGYlWVN-KAccTTDHpcP5UqVSPvtU8w',
    appId: '1:466493882118:ios:886bdccebaf32437dd6887',
    messagingSenderId: '466493882118',
    projectId: 'messenger-bc263',
    storageBucket: 'messenger-bc263.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PaGYlWVN-KAccTTDHpcP5UqVSPvtU8w',
    appId: '1:466493882118:ios:886bdccebaf32437dd6887',
    messagingSenderId: '466493882118',
    projectId: 'messenger-bc263',
    storageBucket: 'messenger-bc263.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBralwIbvKgQnrgmdqdjUD7pn2psf2jSDA',
    appId: '1:466493882118:web:aa2e4707481fbf2add6887',
    messagingSenderId: '466493882118',
    projectId: 'messenger-bc263',
    authDomain: 'messenger-bc263.firebaseapp.com',
    storageBucket: 'messenger-bc263.appspot.com',
    measurementId: 'G-GK6X9FCS0P',
  );
}
